#ifndef _BLOOM_DEFINITION_H
#define _BLOOM_DEFINITION_H

#define BLOOM_USE_13_TAP_FILTER 1
#define BLOOM_USE_TENT_UPSAMPLE 1

#define BLOOM_THRESHOLD 0.25f
#define BLOOM_CLAMP 65000.0f
#define BLOOM_SOFT_KNEE 0.5f
#define BLOOM_DIFFUSION 7.0f
#define BLOOM_INTENSITY 0.5f

#endif